FROM ubuntu:22.04

# Set timezone:
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone

#ARG SSH_PRIVATE_KEY
RUN apt-get update && apt-get install -y tzdata curl pip wget git unzip ffmpeg vim zip && rm -rf /var/lib/apt/lists/*
RUN pip install virtualenv

ENV VIRTUAL_ENV /env
ENV PATH /env/bin:$PATH

#RUN virtualenv venv

RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash
RUN apt-get -yq install nodejs
WORKDIR /server

COPY . /server

RUN npm install -g npm
RUN npm install

# clone YOLOv5 repository
RUN git clone https://github.com/ultralytics/yolov5.git
WORKDIR yolov5/

# install dependencies
RUN pip3 install -r requirements.txt
RUN pip3 install tensorflowjs
RUN pip3 install simple_image_download
RUN pip3 install bing_image_download

# convert model to tensorflow.js format
#python export.py --weights yolov5s.pt --include tfjs